### ISSUE TITLE
unexcepted interruption while using c_pins

### ISSUE THREAD

**Issue by deepme1997** [ruykaji/lefdef-python#1]
Hi ruykaji:

I read a lef file and try to get the pins information of the first cell.  The cell contains 8 pins, and I want to get all information of  those pins. See below codes:
from lefdef import `C_LefReader`
lef_reader = `C_LefReader()`
lef = `lef_reader.read("_LefPath_")`
i  = `0`
pins = `lef.c_macros[i].c_pins`
`print(pins[0].c_name)`
`print(pins[7].c_name)`
`print(pins[8].c_name)`
`print(pins[9].c_name)`
and result is : 

`b'VSS'`
`b'VBB'`
`b'\n'`
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

As you see, when index num < 8 , everything seems right, when index num = 8, I get a wrong return, when index num = 9, procedure inturrupt. 

Why I konw this bucause I don't konw excact num of pins, so I try index num form 0 to 9. if I konw how many pins the cell contains, I may miss this error.

would you mind adding a feature that could tell how many pins of  any cell when using "lef.c_macros[i].c_pins", like"lef.c_num_macros" tells the num of cells. whats more is the wrong return when  index num = 8, "b'\c" is returned, it seems like a little mistake in text reading.

Best wishes~

**Comment by ruykaji** [comment]
@deepme1997 There is actiually `c_num_pins` method for `C_Lef_Macro` class. So you should able to get it using `lef.c_macros[i].c_num_pins`.

If you have 8 pins the indexes lies within range from 0 to 7, so you just can to write something like :
```python
from lefdef import C_LefReader

lef_reader = C_LefReader()
_lef = lef_reader.read("_LefPath_")

for i in range(_lef.c_macros[0].c_num_pins):
    print(_lef.c_macros[0].c_pins[i].c_name)
```

If you have any other  questions fell free to ask.

**Comment by deepme1997** [comment]
Thank you so much,  it’s a nice work and helpful for me :）
